### ISSUE TITLE
Separate active profile from current loaded profile

### ISSUE THREAD

**Issue by nuggettowin** [calamity-inc/Stand-Feedback#12]
Currently, after you load a different profile, it automatically becomes your active profile. Might be nice to separate it so you don't have to load your preferred active profile first before closing the game for next time.

**Comment by LordByronRS** [comment]
This has to be the weirdest change in a long time. The way I fixed it, is by making the file which saves the current active profile read-only.

**Comment by Sainan** [comment]
Yeah, this is a bit of a weird one. Initially when I made profiles, I must've thought that the state exists in a vacuum and can just be loaded without activating the respective profile, but there were a few edge-cases where this was proven to be wrong, so loading a profile had to change the active profile.

Now, recently I made it so this change of active profile is also committed to the Meta State, since I thought it was weird that these would come to be disjointed, which now leads to the behaviour of the last-loaded profile being loaded the next time you inject Stand.

Anyway, I definitely understand that this is a bit confusing. I'll make some changes to the profile system in 116 to alleviate this.
