### ISSUE TITLE
Add free shopping like cherax has. it would be good for not having to gring money but being able to own things in game without having to spawn them plus you actually buy them.

### ISSUE THREAD

**Issue by xPandaxWeeperx** [calamity-inc/Stand-Feedback#320]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sainan** [comment]
Yeah, I understand the desire for this, and it's an idea I've toyed around with, but the problem is, you will be sending modified transactions to R* servers, so the odds of this being undetected is practically 0. I guarantee you, Rockstar are already monitoring everyone who is using this feature, and they will be banned with the next wave in like 3 months or so.
